---
title: SDMA Radar
comment: Radar for SDMA flag 3, approach only, run gap 25.00s
run_gap: 2000
min_speed: 30
angle: 0
sensitivity: 2
direction: 1
rate: 0
units: 0
device: /dev/ttyS0
port: 251
debug: 0
save_ver: 30
port_slow: 252
update: 300
speed_log: /var/log/radar/radar1
mqtt_clientname: Radar_Sender_Huntley1
mqtt_topic: radar/huntley/1
mqtt_server: www.dd.id.au
mqtt_port: 443
mqtt_transport: websockets
mqtt_user: huntley_send
mqtt_pass: Ymv7fEfrBcBDbBx8
mqtt_path_base: /mqtt
...
